
FROM python:2.7

RUN echo "Warning python 2.7 will be deprecated, so you have to migrate it to 3.6"
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y
RUN apt-get install -y build-essential
RUN apt-get install -y gcc
RUN apt-get install -y git
RUN apt-get install -y dos2unix
RUN apt-get install -y libpq-dev
RUN apt-get install -y make

RUN apt-get install -y python-pip
RUN apt-get install -y python2.7
RUN apt-get install -y python2.7-dev
RUN apt-get install -y vim

RUN mkdir x
ENV src /x
WORKDIR ${src}
#clone project from git and try to build it

run git clone https://github.com/vasanthkalingeri/CommercialDetection.git
CMD ['cd',' CommercialDetection/']
run ./dependencies.sh
run echo "NOW YOU CAN BUILD AN APP for tracking ads statistics throughout whole world"

